spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.authentication-database=admin
spring.mongodb.username=admin
spring.mongodb.password=password
spring.mongodb.database=springtutorialmongodb
spring.mongodb.uri= mongodb://admin:password@localhost:27017/springtutorialmongodb?authSource=admin
